### ISSUE TITLE
Order of execution: Network units before users

### ISSUE THREAD

**Issue by tazjin** [coreos/coreos-cloudinit#215]
Hej!

When trying to deploy a cloud-config on a fresh machine that requires a network unit to be set up for connectivity, the initial deployment fails for me because I'm using the Github key import in the same file.

CoreOS will try to fetch the Github userkeys before it sets up the network, and will then never set up the network, fail and just leave the machine in and unusable state.

Cheers!

**Comment by crawford** [comment]
Ignition fixes this issue. I don't think we'll be fixing it in coreos-cloudinit.
