### ISSUE TITLE
Cloudinit, the next generation

### ISSUE THREAD

**Issue by marineam** [coreos/coreos-cloudinit#221]
At this point we have pretty well explored all of the massive shortcomings of our current design. Some major points include:

**Configuring a system half-way through booting is dependency hell.**
- Classic example: Networking. Some configurations need to configure networking, some configurations depend on networking to fetch data. Right now we split the difference by handling both use-cases poorly.
- An etcd cluster *must* be configured before etcd starts. This includes setting discovery URL, node name, address information, etc. The next etcd version will begin to chip away at these problem points but this takes time and some configuration like discovery URL will always remain. Creating a strict dependency between cloudinit and etcd wold resolve this but it is currently impossible due to limitations of go-systemd and the simple unpredictability of cloudinit sources.
- Interacting with systemd via yaml is not intuitive or "discoverable" by new users. Mix this with the complex ways systemd units are organized in the filesystem and the difference between "start" and "enable". The result is a system that is really difficult to grok without extensive previous systemd knowledge.

**Configuration sources are diverse, buggy, and unpredictable.**
- OpenStack platforms demonstrate everything that can go wrong:
  - Config drive or metadata service, or neither, or both. We must detect what to use, we must not allow the two to conflict.
  - Metadata is unreliable. Addressing information may be available, it may not. It may be in one part of the data but not another.
- Vagrant is a whole different type of special. There is no configuration information available during boot. The system is expected to wait until vagrant logs in via SSH and starts poking around the system.
- As you probably already know, people. Cloudinit takes input from both platform provided metadata and user provided configs. It is easy to make mistakes and people always do. Some common problems:
  - got `#cloud-config`?
  - white space, meaningless to everyone except python programmers
  - `-` vs. `_`: FIGHT
  - When things go wrong the error is lost somewhere in the system journal.
  - When things go wrong everything does, user data can prevent cloudinit from interpreting system data.

**What next?**
- [X] Run cloudinit from the initrd. https://github.com/coreos/ignition
  - *Pros*: Avoids a wide variety of dependency issues by configuring the system *before* it boots.
  - *Cons*: How long do we wait for configuration sources? What does `command: restart` mean?
- [X] Cloud config validator.
  - [X] A web interface for checking configs, most practical way to assist users of cloud provider web interfaces. https://coreos.com/validate
     - *Pros*: Everyone will love it! 
     - *Cons*: A web form for submitting root password hashes to a third party, what could go wrong?
  - [X] Stand alone validator. Useful for cloud API users, avoids that whole submitting to a third party issue. #254
- [ ] Turn coreos-install into a real installer.
 - [X] Use validator to check cloud configs. https://github.com/coreos/init/pull/144
 - [ ] Add interactive mode to allow setting passwords so users don't have to use a cloud config at all.
  - *Pros*: YES.
  - *Cons*: Aww, we have to write a Linux distro installer?
- [ ] More permissive configuration parsing. 
  - [X] Accept both `-` and `_`.  #45 
  - [ ] Merge different metadata sources in hopes that values missing from one will exist in another.
  - [X] Fix/replace the yaml parser so it is possible to give users useful errors and warnings.
- [ ] Report errors to users in loud and obvious ways.

**Thoughts?**
Please fix/update/expand this document, link to related bugs, etc.

**Comment by crawford** [comment]
FYI, [Ignition](https://github.com/coreos/ignition) exists. This is the next generation provisioning utility for CoreOS. It runs from the initrd, uses JSON instead of cloud-config-flavored-YAML, and has a lot of new capabilities (like reformatting the root partition). It has already addressed many of these issues.
