### ISSUE TITLE
Additional EBS Stores Cannot Be Formatted, Mounted

### ISSUE THREAD

**Issue by jcderr** [coreos/coreos-cloudinit#230]
My EC2 launch config for a docker "builder" instance (intended for the team to use to build new images for deployment) includes a supplemental 100gb EBS store provisioned on xvdf. If I use the directions [here](https://coreos.com/docs/cluster-management/setup/mounting-storage/) and substitute in /dev/xvdf for my supplemental volume, launching the instance breaks.

EC2 will launch the instance, but it will fail to install the EC2 private key, I'll be unable to SSH into the machine as `core`, and the format and mount units will not be loaded onto the instance. Oddly, however, the users I specify in my cloud-init, which have their authorized keys loaded from github, WILL be able to access the server. The logs and journals don't seem to belie any information about what may be stopping the process.

[My user-data](https://gist.githubusercontent.com/jcderr/b01900e246825177c9fb/raw/651c770f7767d0dc300710bae2b8ecd4a73cc28b/gistfile1.txt) works perfectly if this extra volume is not present on the instance.

```
#cloud-config

users:
  - name: <user 1>
    coreos-ssh-import-github: <user 1>
    groups:
      - sudo
      - docker
  - name: <user 2>
    coreos-ssh-import-github: <user 2>
    groups:
      - sudo
      - docker
coreos:
  fleet:
    metadata: environment=admin
  etcd:
    discovery: https://discovery.etcd.io/< id removed >
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: format-ephemeral.service
      command: start
      content: |
        [Unit]
        Description=Formats the ephemeral drive
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/sbin/wipefs -f /dev/xvdf
        ExecStart=/usr/sbin/mkfs.btrfs -f /dev/xvdf
    - name: var-lib-docker.mount
      command: start
      content: |
        [Unit]
        Description=Mount ephemeral to /var/lib/docker
        Requires=format-ephemeral.service
        After=format-ephemeral.service
        Before=docker.service
        [Mount]
        What=/dev/xvdf
        Where=/var/lib/docker
        Type=btrfs
```

**Comment by crawford** [comment]
It sounds like this is not an issue specifically with cloudinit. I'm going to close this issue.
