### ISSUE TITLE
Digitalocean cloud config script has DOS line endings

### ISSUE THREAD

**Issue by marclennox** [coreos/coreos-cloudinit#289]
This may be a DO issue, but I thought I'd post here first in case it has something to do with coreos-cloudinit.

I'm trying to launch a CoreOS instance on DO with a bash script user-data.  The exact same script works fine for me on AWS and Azure, however on DO the script execution fails.

The reason it fails is that the script is being written to disk with ^M$ line endings, so the bash is adding the ^M part to the command.

Any ideas how to work around this?

**Comment by crawford** [comment]
@marclennox DigitalOcean has fixed their web UI.

**Comment by marclennox** [comment]
Great thanks for the update 



—
