### ISSUE TITLE
cloud-init fails to parse user_data

### ISSUE THREAD

**Issue by vickyramuk** [coreos/coreos-cloudinit#303]
Hi I have been trying to bring up a coreOS cluster using openstack heat orchestration. with Heat one can specify the user data as resources.

I am able to create a coreos cluster when I use cloud config resource for user data. one can also specify a software config resource as user data something like 
 #!/bin/sh
 echo "The two is bar" > /tmp/two 

Both of them do not give any problem. But when I try to club them into another resource of type multipartmime resource and use that as the user_data ,the clout-init fails to parse the user_data with the below error message.

 
Jan 22 22:46:19 host-10-20-30-75 coreos-cloudinit[532]: Failed to parse user-data: Unrecognized user-data header: Content-Type: multipart/mixed; boundary="===============2575908242629671258=="
Jan 22 22:46:19 host-10-20-30-75 coreos-cloudinit[532]: Continuing...
Jan 22 22:46:19 host-10-20-30-75 coreos-cloudinit[532]: Processing cloud-config from meta-data
Jan 22 22:46:19 coreosstack-tvecoreos01-yhxuulyjbzh4.novalocal coreos-cloudinit[532]: 2015/01/22 22:46:19 Set hostname to coreosstack-tvecoreos01-yhxuulyjbzh4.novalocal
Jan 22 22:46:19 coreosstack-tvecoreos01-yhxuulyjbzh4.novalocal coreos-cloudinit[532]: 2015/01/22 22:46:19 Authorized SSH keys for core user
Jan 22 22:46:19 coreosstack-tvecoreos01-yhxuulyjbzh4.novalocal coreos-cloudinit[532]: 2015/01/22 22:46:19 Updated /etc/environment
Jan 22 22:46:19 coreosstack-tvecoreos01-yhxuulyjbzh4.novalocal systemd[1]: oem-cloudinit.service: main process exited, code=exited, status=1/FAILURE
Jan 22 22:46:19 coreosstack-tvecoreos01-yhxuulyjbzh4.novalocal systemd[1]: Failed to start Cloudinit from EC2-style metadata.
Jan 22 22:46:19 coreosstack-tvecoreos01-yhxuulyjbzh4.novalocal systemd[1]: Unit oem-cloudinit.service entered failed state.

any inputs are much appreciated.

**Comment by crawford** [comment]
coreos-cloudinit does not support multipart userdata. It needs to either be a script (beginning with "#!") or a cloud-config (beginning with "#cloud-config"). If you need both, your best bet is to include the scripts as oneshot services in your config.

**Comment by vickyramuk** [comment]
thanks for the real quick reply crawford. 

So here with coreos, if I need to have few commands run by cloud-init along with cloud-config, it should be inside the cloud-config as bootcmd: or runcmd: is it? or did you mean something else.

**Comment by crawford** [comment]
We don't support the full cloud-init spec (as you found out) and don't support bootcmd or runcmd. You'll want to use coreos.units. i.e.:

```yaml
#cloud-config

coreos:
  units:
    -
      name: hello.service
      runtime: true
      command: start
      content: |
        [Service]
        ExecStart=/usr/bin/echo Hello World!
```

You can use https://coreos.com/validate/ to help quickly verify that your config is at least valid.

**Comment by vickyramuk** [comment]
oh my bad. I will try with the coreos units. thanks again.

**Comment by crawford** [comment]
No problem. Let me know if you run into trouble.
