### ISSUE TITLE
Validate argument removed

### ISSUE THREAD

**Issue by rboswell** [coreos/coreos-cloudinit#309]
At some point the -validate argument was removed from the Master branch and is causing the coreos-install script to fail at https://github.com/coreos/init/blob/master/bin/coreos-install#L203. I'm on CoreOS 494.5.0 and coreos-cloudinit 0.10.9.

**Comment by crawford** [comment]
The -validate argument was introduced later on. You'll need to use an older version of coreos-install if you want to install that old stable build. Otherwise, you can install the latest stable (currently 522.6.0) with the latest install script.

**Comment by rboswell** [comment]
Ugh, duh, sorry about that, I didn't realize I was using an old install ISO. Keep walking, nothing to see here....
