### ISSUE TITLE
Feature-request: Constants in cloud-init

### ISSUE THREAD

**Issue by hookenz** [coreos/coreos-cloudinit#327]
So often I'm having to repeatedly put the same value in multiple places inside my cloud-config files. 

I think it would be a useful addition to be able to do have some kind of substitution feature for constant values for use only within cloud-config

I notice a debate right now regarding environment variable substitution.  This is not that.  I'm suggesting being able to define constants and use them later in the cloud-config file.  

Something like the following example

    #cloud-config

    constants:
      - name: PUBLIC_IF
        value: eth0

    write_files:
      - path: /var/lib/iptables/rules-save
        permissions: 0644
        owner: root:root
        content: |
          *filter
          :INPUT DROP [0:0]
          :FORWARD DROP [0:0]
          :OUTPUT ACCEPT [0:0]
          -A INPUT -i ! ${PUBLIC_IF} -j ACCEPT
          -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
          COMMIT

**Comment by ibukanov** [comment]
I do not see why this feature is necessary as this is already can be done - just put a shell script into your config that generates the file that you need and schedule to run this script at the necessary point. For example, in your case you could have something like:
```
write_files:
  - path: /etc/generate-local-iprules
    permissions: 0755
    owner: root:root
    content: |
      #!/bin/bash
      PUBLIC_IF=eth0
      cat > /var/lib/iptables/rules-save <<EOF
      *filter
      :INPUT DROP [0:0]
      :FORWARD DROP [0:0]
      :OUTPUT ACCEPT [0:0]
      -A INPUT -i ! ${PUBLIC_IF} -j ACCEPT
      -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
      COMMIT
      EOF
  - path: /etc/systemd/system/iptables-restore.service.d/call-generator.conf
    permissions: 0644
    owner: root:root
    content: |
[Service]
ExecStartPre=/etc/generate-local-iprules
```

Here the second file modifies iptables-restore.service to call the script before systemd run iptables-restore. As a bonus for ultimate auto-configuration the script can use the ip command to decide what is a public interface.

**Comment by hookenz** [comment]
Thanks, I requested this before I even knew cloud-config.yml could be a script that also calls cloud-init again with variable substitutions.  So yes, I don't think it's entirely necessary.

**Comment by crawford** [comment]
YAML anchors and aliases can also help with this.
