### ISSUE TITLE
Failed to apply cloud-config: Unable to parse file permissions "484" as integer on Vagrant

### ISSUE THREAD

**Issue by tleyden** [coreos/coreos-cloudinit#328]
To reproduce:

```
$ git clone git@github.com:tleyden/coreos-vagrant.git
$ cd coreos-vagrant
$ cp config.rb.sample config.rb
$ cp user-data.sample user-data
$ vagrant up && vagrant ssh core-01 -- -A
```

This clones my fork which has some customization of the user-data file, in particular [adding a few files](https://github.com/tleyden/coreos-vagrant/blob/master/user-data.sample#L4-L54) via the write-files directive. 

After ssh'ing in, I get errors when listing machines:

```
core@core-01 ~ $ fleetctl list-machines
2015/03/26 18:14:00 INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: dial tcp 127.0.0.1:4001: connection refused
2015/03/26 18:14:00 ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/machines}, retrying in 100ms
```

Looking into the journalctl logs, I see the following error:

```
Mar 26 18:12:38 core-01 coreos-cloudinit[859]: Failed to apply cloud-config: Unable to parse file permissions "484" as integer
Mar 26 18:12:38 core-01 systemd[1]: user-cloudinit@var-lib-coreos\x2dvagrant-vagrantfile\x2duser\x2ddata.service: main process exited, code=exited, status=1/FAILURE
Mar 26 18:12:38 core-01 systemd[1]: Failed to start Load cloud-config from /var/lib/coreos-vagrant/vagrantfile-user-data.
```

[Full journalct logs](https://gist.github.com/tleyden/84296d7a90b517ae4efa)

I notice that something has changed the values in the user-data file:

```
$ diff user-data user-data.sample
7c7
<   permissions: 420
---
>   permissions: 0644
13c13
<   permissions: 420
---
>   permissions: 0644
19c19
<   permissions: 420
```

The following workaround seems to work for me:

```
$ sed -i '' 's/420/0644/' user-data
$ sed -i '' 's/484/0744/' user-data
$ vagrant reload --provision
```

Any idea why the user-data file is getting the file permissions mangled?

Version: 633.1.0 alpha

**Comment by crawford** [comment]
`0o644 == 420`. Something is doing a base conversion for you. It looks like this happens before the OS even boots.

The other option is to quote the value and make it a string. Yes, this is accepted by coreos-cloudinit. :(

**Comment by tleyden** [comment]
> Something is doing a base conversion for you. It looks like this happens before the OS even boots.

Any ideas?  I guess that would leave something in Vagrant?

> The other option is to quote the value and make it a string

I'll give that a try.

**Comment by jmreicha** [comment]
Just ran in to this issue, quoting the permissions seems to work, although it would be nice not to deal wth them.
