### ISSUE TITLE
etcd2 section

### ISSUE THREAD

**Issue by philips** [coreos/coreos-cloudinit#329]
We want to have an etcd2 section that configures a cluster using the etcd2 native flags:

https://github.com/coreos/etcd/blob/master/Documentation/configuration.md#configuration-flags

This list does not include any of the deprecated flags from etcd 0.4 and cloud-init shouldn't include them either.

**Comment by philips** [comment]
There is only one open question around this: do we set ETCD_NAME to `%m` by default or do we do leave it as-is.

**Comment by marineam** [comment]
I had been thinking that cloudinit still wrote a dropin to set ETCD_NAME instead of just including that default in the unit. Now days it is in the etcd unit which is much less magical so I'm fine with sticking with that.
