### ISSUE TITLE
coreos-ssh-import-github-users uses API to get keys, which is rate-limited

### ISSUE THREAD

**Issue by JeanMertz** [coreos/coreos-cloudinit#334]
```
$ curl https://api.github.com/users/JeanMertz/keys
{
  "message": "API rate limit exceeded for xx.xx.xx.xx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

```
$ curl https://github.com/JeanMertz.keys
ssh-rsa AAAAB3NzaC1yc2EA...
```

Same response, but different endpoints. When doing lots of key lookups fast, you get errors and cloud-config fails. With the latter endpoint, this is not the case.

**Comment by crawford** [comment]
I think this is the final nail in the coffin for this feature. Depending on a remote service (which may be currently under DDoS by China) for your machine setup is such a bad idea. I wish we had never introduced this.

I've deprecated these options and encourage you to bake the keys directly into your config.

**Comment by JeanMertz** [comment]
@crawford agreed. It did make it easier for developers to change/add keys, but it's also a security issue so I guess it's best to manually add them.
