### ISSUE TITLE
Feature-request: populate private_ipv4 and/or public_ipv4 for bare metal installs?

### ISSUE THREAD

**Issue by hookenz** [coreos/coreos-cloudinit#337]
It'd be really nice to be able to populate these environment variables.  $private_ipv4 and/or $public_ipv4 when systemd brings a network interface up.

I've been trying to think of a way to do it without any changes to cloud-config itself such as running a script.

Any ideas?  could it be added to cloud-init somehow

**Comment by hookenz** [comment]
I've found a workaround which does the job for now.  https://gist.github.com/crawford/ed7e954bfddd3394c775
This should be part of the official docs.  If you name it /usr/share/oem/cloud-config.yml.  It'll work.

**Comment by devurandom** [comment]
This is really important to us, too.

**Comment by crawford** [comment]
This will not be fixed by coreos-cloudinit. There is no way for us to know which interfaces should be public and which should be private. The underlying issue is , however, solved in Ignition. We are close to cutting the first release and I encourage you to test it out once it's in the image.

**Comment by devurandom** [comment]
For the curious: Very basic information about Ignition can be found in a [blogpost from CoreOS Fest] and in its [GitHub repository].

[blogpost from CoreOS Fest]: https://coreos.com/blog/coreos-state-of-the-union-coreosfest/
[GitHub repository]: https://github.com/coreos/ignition

**Comment by hookenz** [comment]
Awesome.  I like the look of ignition.  cloud-init is good, but applies things a little late for things like module loads which requires restarting some daemons.  So this looks like a great solution.
