### ISSUE TITLE
Bare metal environment substitution to with IP and starting etcd in docker?

### ISSUE THREAD

**Issue by hookenz** [coreos/coreos-cloudinit#338]
I'm trying to set up a bare metal setup of CoreOS and using the following script.  Unfortunately, it doesn't work despite EnvironmentFile being specified, the IP doesn't come through yet it is in /etc/environment.

Running the script shows /etc/environment being written successfully.  The other problem is that although I tried creating this file as etcd.service rather than etcd2.service.  It would seem that fleet kicks off etcd (old version) instead of the new one provided through docker. 

How can I make this work?  I'm wanting to keep everything in one place if possible.

    #!/bin/sh
         
    workdir=$(mktemp --directory)
    trap "rm --force --recursive ${workdir}" SIGINT SIGTERM EXIT

    cat << EOF > ${workdir}/cloud-config.yml
    #cloud-config

    ssh_authorized_keys:
      - ssh-rsa [rsa-key...]
    coreos:
      units:
        - name: etcd2.service
          command: start
          content: |
            [Unit]
            Description=etcd2 container
            After=docker.service
            
            [Service]
            EnvironmentFile=/etc/environment
            ExecStartPre=-/usr/bin/docker kill etcd2
            ExecStartPre=-/usr/bin/docker rm etcd2
            ExecStartPre=/usr/bin/docker pull quay.io/coreos/etcd:v2.0.8
            ExecStart=/usr/bin/docker run -p 4001:4001 -p 2380:2380 -p 2379:2379 --name etcd2 quay.io/coreos/etcd:v2.0.8 \
              -name \${ETCD_NAME} \
              -advertise-client-urls http://\${private_ipv4}:2379,http://\${private_ipv4}:4001 \
              -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 \
              -initial-advertise-peer-urls http://\${private_ipv4}:2380 \
              -listen-peer-urls http://0.0.0.0:2380 \
              -initial-cluster-token etcd-cluster-1 \
              -initial-cluster \${ETCD_PEERS} \
              -initial-cluster-state new
            ExecStop=/usr/bin/docker stop etcd2
        - name: fleet.service
          command: start
    EOF
         
    get_ipv4() {
        IFACE="${1}"
     
        local ip
        while [ -z "${ip}" ]; do
            ip=$(ip -4 -o addr show dev "${IFACE}" scope global | gawk '{split ($4, out, "/"); print out[1]}')
            sleep .1
        done

        echo "${ip}"
    }
        
    export COREOS_PRIVATE_IPV4=$(get_ipv4 enp2s0)
    coreos-cloudinit --from-file="${workdir}/cloud-config.yml"

**Comment by kipotz1986** [comment]
${private_ipv4} and ${public_ipv4} templating is not supported for bare metal deployment
