### ISSUE TITLE
Inconsistent key names in yaml file

### ISSUE THREAD

**Issue by hookenz** [coreos/coreos-cloudinit#340]
Some keys have underscore, some have hyphen.  It's easy to make mistakes.  Cloud-init should accept, one or the other or either one for key names.

For example in the fleet section.

etcd_servers or etcd-servers

**Comment by crawford** [comment]
Hyphens and underscores are interchangeable. The docs should pick one and stick with it though.

**Comment by hookenz** [comment]
Thanks for the clarification.  I did wonder later but I thought I'd point that out.
