### ISSUE TITLE
Order user-configvirtfs before systemd-networkd

### ISSUE THREAD

**Issue by ibukanov** [coreos/coreos-cloudinit#343]
As user-configvirtfs does not depend on networking, it would be nice to order systemd-networkd after  user-configvirtfs. This way even on the first  boot the configured host name will be properly used for DHCP, the static ip can be configured for the first boot, network-related units can be written under /run, not /etc, to ensure that reboot brings the system into a clean state etc.

**Comment by crawford** [comment]
Services within a cloud-config may depend on networking though. All services are started serially by coreos-cloudinit and if they depend on networking, but coreos-cloudinit runs before networking, it will deadlock. These issues are addressed by [Ignition](https://github.com/coreos/ignition) which will begin shipping in CoreOS in the coming months.

**Comment by ibukanov** [comment]
My problem with Ignition is that it distinguishes strongly the first boot from other boots. What I want is the opposite: a non-persistent configuration that is put under /run on each boot against a clean state. I understand the issues with cloud-init, but it seems that they come from poor systemd integration rather then inherent deficiencies of the design. That is, cloud-init should be a notify service that tells systemd that it is ready after it creates systemd units defined in the config but before it starts units . Then there would be no problems with ordering networking after the config is ready.

**Comment by crawford** [comment]
There is no distinction between first boot and subsequent boots with Ignition (from userspace's point of view). There is, however, a distinction with coreos-cloudinit. In fact, this distinction was one of the driving motivators behind the creation of Ignition.

The real issue with networking and coreos-cloudinit, is the fact that some data sources require network to fetch the configuration. If you also want to configure the network, you end up in a complex chicken-and-egg scenario. Ignition handles this by using DHCP within the initramfs and then dropping the network config before pivoting. This way, networkd just follows whatever config was written by Ignition.

Achieving the scenario you've described is trivial with Ignition. In fact, you could even take it one step further and set it up to reformat the disks on every boot. That way you truly have a clean slate.

**Comment by ibukanov** [comment]
@crawford wrote:
> Achieving the scenario you've described is trivial with Ignition. 
Does it mean that Ignition mounts /run as tmpfs so I can start populating it with unit files for use with systemd later? And presumably it avoids running DHCP twice during boot unless the user-supplied config wants it?

> In fact, you could even take it one step further and set it up to reformat the disks on every boot. 

Paraphrasing the system should be as stateless as possible, but not more stateless. I.e. I want my precious data stored persistently on a system where a reboot is sufficient to recover from configuration mistakes.

**Comment by crawford** [comment]
> Does it mean that Ignition mounts /run as tmpfs so I can start populating it with unit files for use with systemd later?

Ignition isn't able to write anything directly to /run because it's not mounted in the initramfs. It is mounted later in the boot process.

> And presumably it avoids running DHCP twice during boot unless the user-supplied config wants it?

Ignition only runs early in the first boot (this is key). During that first boot, it will DHCP twice (assuming that's the way the user has configured the network), but on subsequent boots it will only configure the network once.

**Comment by ibukanov** [comment]
> Ignition isn't able to write anything directly to /run because it's not mounted in the initramfs.

Hm, but how it is then could help with stateless non-persistent config stored in RAM that I can get now with minimal patching from cloud-init?

> Ignition only runs early in the first boot (this is key)... but on subsequent boots it will only configure the network once.

This is confusing. Does it mean that Ignition has a special phase that runs really early on the first boot but on subsequent boots this phase is not activated and Ignition behaves like cloud config currently?

**Comment by crawford** [comment]
> Hm, but how it is then could help with stateless non-persistent config stored in RAM that I can get now with minimal patching from cloud-init?

That is a little trickier to pull off, but I don't see a solid reason to do that. That pattern makes a lot of sense when using cloud-init because that's the best way to achieve deterministic behavior. With Ignition, this is no longer neccessary (because Ignition runs before the first boot).

> This is confusing. Does it mean that Ignition has a special phase that runs really early on the first boot but on subsequent boots this phase is not activated

Basically. It runs from the initramfs, which happens before systemd _begins_ to run. This way, you have the opportunity to create any files that systemd or networkd need.

**Comment by ibukanov** [comment]
My appreciation for non-persistent config in RAM had started when a bug in my custom ssh config file made a cloud VM inaccessible. Fortunately the VM had only test data for development so the lesson was cheap.

The appreciation grew even stronger when on CoreOS I temporally enabled static IP via adding network units to the config file. Then I removed those units from the file and spend some trying to understand why the machine still uses the old static IP. Of cause it was because cloud-init left the older files as is on the disk! That lead to this bug.

Note the whole issue is not applicable to stateless VM when one can just kill an instance and start another one from scratch. But when VM holds persistent data (where CoreOS case is not that strong), I see that config that stays in a memory is rather important. In case of troubles or bugs it allows on reboot trivially disable all the services and safely rsync data.

In any case, Ignition at least is not worst than cloud-init as on the first boot I could install my own config software that creates non-persistent configs. But it would be nice to have my user case covered.
