### ISSUE TITLE
order services after cloudinit

### ISSUE THREAD

**Issue by ibukanov** [coreos/coreos-cloudinit#346]
#221 suggest to run cloudinit from initrd. This is an overkill if one just wants to order initialization of some services after the config is processed. 

Following http://lists.freedesktop.org/archives/systemd-devel/2015-May/032045.html the idea is to create a special disabled target like `user-config-ready`, make sure that all services like docker, fleet, etcd, sshd that can be configured are wanted by this target and should not be started by anything that starts before cloudinit. Then, after the cloudinit finishes the config, it will call `systemctl daemon-reload` and then `systemctl start run-after-config-is-ready`.

This ensures proper ordering and allows for the config to fully customize the services including disabling them or ordering them in particular order. Moreover, this can be done by adding files under /run so the configuration changes stays only until the next reboot minimizing the amount of persistent state.

Compared with initrd this also allow to continue to depend on systemd-networkd to bring the networking up when the config is downloaded from other hosts.

**Comment by crawford** [comment]
Ignition already exists. Running from the initrd allows us to do things like reconfigure the network, partition disks, and format filesystems. This is going to be the way forward.
