### ISSUE TITLE
Launcing CoreOS AMI on EC2

### ISSUE THREAD

**Issue by patrickbcullen** [coreos/coreos-cloudinit#348]
We recently started experiencing problems launching CoreOS AMIs on EC2. The instance will launch but the oem-cloudinit.service fails with the following error:

Jun 02 14:53:29 ip-10-128-133-231 coreos-cloudinit[567]: Failed to apply cloud-config: exit status 1
Jun 02 14:53:29 ip-10-128-133-231 systemd[1]: oem-cloudinit.service: main process exited, code=exited, status=1/FAILURE
Jun 02 14:53:29 ip-10-128-133-231 systemd[1]: Failed to start Cloudinit from EC2-style metadata.

This happens without any user data, just launching a regular CoreOS AMI from the EC2 console.

Because the issue is in oem-cloudinit.service before the SSH key is installed the only way to troubleshoot is to attach the EBS volume to a working instance and read the system journal. This makes it very difficult to troubleshoot. Is there anyway to disable the oem-cloudinit.service? It appears to be baked in the EC2 AMI. I have a replacement script I wrote using a user data bash script, but it never runs it because it fails earlier in the oem-cloudinit.service before it runs my user data script.

**Comment by crawford** [comment]
The oem-cloudinit.service is what does all of the communication with AWS, so you don't want to disable that. On what version of CoreOS are you seeing this issue? I was able to spin up both 647.2.0 (current stable) and 695.0.0 (current alpha) just fine.

**Comment by patrickbcullen** [comment]
We see the problem with both stable and alpha. What region are you using? We have seen the problem in us-east-1, but I have not tried us-west-2.

**Comment by crawford** [comment]
I'm using us-west-2, but the images should be identical between regions. Can you give me more details about the environment (AMI, VPC settings, etc.) and the output of `journalctl -b -u oem-cloudinit.service --no-pager`?

**Comment by patrickbcullen** [comment]
We found the problem. Someone changed our DHCP option set in the VPC to have domain-name with a comma separated list. This is invalid and caused the set hostname in cloud-init to fail. Unfortunately, cloud-init stops at that point and does not install the SSH keys so you cannot SSH to the instance. Other linux distributions like Ubuntu and Centos don't have this problem. They continue past that error and install the SSH keys.

**Comment by crawford** [comment]
OK, this is good to know. I'll have to take a look into that.
