### ISSUE TITLE
cloud-config strict init mode

### ISSUE THREAD

**Issue by DJviolin** [coreos/coreos-cloudinit#359]
Is it possible somehow to force my CoreOS to read the user_data file at every boot?

**Comment by crawford** [comment]
coreos-cloudinit does read your platform's user_data on every boot. What provider are you using?

**Comment by DJviolin** [comment]
I'm using Virtualbox. Looks like it's working now. Most of the time the refreshed data will be attached at the second boot. But if I use a brand now VM image, reading at the first time without problem.
