### ISSUE TITLE
cgi script CoreOS cloud-config

### ISSUE THREAD

**Issue by mazad01** [coreos/coreos-cloudinit#360]
Is there a way for using a cgi script to configure the cloud-config for hosts rather than having separate cloud-configs for each unique host?

**Comment by crawford** [comment]
I don't follow. At the end of the day, each machine will need a cloud-config. The contents of that config and the manner in which you generate it are up to you.

**Comment by mazad01** [comment]
Ok, for example, I have a cloud-config that does some puppet initialization, docker configs, and some hosts need a unique static route config. How would I be able to use the same cloud-config but the hosts get their own unique static route entries?

**Comment by crawford** [comment]
If you truely need to use the same config, one of the services in your config would need to query your source of truth (webserver, serial port, config drive, etc.) and set up the default routes. This multi-stage configuration is much more complicated than unique cloud-config and is prone to transient failure at runtime (not good for reliability). My suggestion would be to generate unique cloud-configs for each machine.

**Comment by mazad01** [comment]
> one of the services in your config would need to query your source of truth (webserver, serial port, config drive, etc.) and set up the default routes.

got it, that's what i was looking for. Wasn't really sure how to approach the problem but that makes sense. Thanks for the help
