### ISSUE TITLE
coreos-cloudinit http client timeout too low

### ISSUE THREAD

**Issue by chassing** [coreos/coreos-cloudinit#369]
I want to deploy coreos in our environment via pxe and foreman (http://theforeman.org) as tftp and cloud-config provider. Unfortunally coreos-cloudinit has a too low http client timeout (2 seconds). If I download the cloud-config file via curl it's working but not with "coreos-cloudinit -from-proc-cmdline" 

```
# coreos-cloudinit -from-proc-cmdline
Checking availability of "proc-cmdline"                                         
Fetching user-data from datasource of type "proc-cmdline"                       
2015/08/07 10:29:19 Fetching data from https://foreman.mycomany.com/unattended/provision. Attempt #1                                                    
2015/08/07 10:29:21 Unable to fetch data: Get https:/foreman.mycomany.com/unattended/provision: read tcp X.X.X.X:443: i/o timeout                 
2015/08/07 10:29:21 Sleeping for 100ms...                                       
2015/08/07 10:29:21 Fetching data from https://foreman.mycomany.com/unattended/provision. Attempt #2                                                    
....
```

with curl:
```
# time curl https://foreman.mycomany.com/unattended/provision
[snip]
cloud config file content
[/snip]

real    0m3.935s
user    0m0.023s
sys     0m0.002s
```
I'm using:
```
NAME=CoreOS
ID=coreos
VERSION=758.1.0
VERSION_ID=758.1.0
BUILD_ID=
PRETTY_NAME="CoreOS 758.1.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

@Nosmoht has a simular issue: https://github.com/coreos/coreos-cloudinit/issues/105#issuecomment-101195928

**Comment by crawford** [comment]
It should retry that up to 15 times. Can I see more of the output of that command you ran?

**Comment by chassing** [comment]
Yes you're right, it retries 15 times but every time I get the same error message:
```
Unable to fetch data: Get https:/foreman.mycomany.com/unattended/provision: read tcp X.X.X.X:443: i/o timeout
```

**Comment by marineam** [comment]
I suppose we could increase the timeout from 2 to 5 or 7 seconds. 4 seconds is really the best response time you can get? :(

**Comment by chassing** [comment]
Unfortunately 4 seconds is the best :( but why not increase it to 30 or 60 seconds? I mean it's just a timeout.

**Comment by Nosmoht** [comment]
We had the same setup (Foremam + TFTP + Cloud-config from Foreman) and the same issue. We simple fixed it by creating a custom CoreOS ISO where we patched the file and set the timeout to 10s which was enough in our case. As we build only the installation medium this isn't a big thing. You can install whichever Version of CoreOS you want.

Hope this helps

**Comment by crawford** [comment]
Fixed via https://github.com/coreos/coreos-cloudinit/pull/374.
