### ISSUE TITLE
Support floppy drives

### ISSUE THREAD

**Issue by felixbuenemann** [coreos/coreos-cloudinit#377]
The CoreOS [cloud-config docs](https://coreos.com/os/docs/latest/config-drive.html) say that config data can be provided using either an iso9660 or fat filesystem, as long as the volume is named config-2.

I created a floppy image with the appropriate directory structure using fat-12 filesystem and volume label "CONFIG-2" (fat-12/fast-16 volume names are always uppercase), attached it to /dev/fd0 in the VM, but it was not detected.

The same config data put on an iso image was detected just fine.

I think supporting floppy images would be a good idea, especially for physical servers. Because most servers allow attaching floppy images remotely and the cd drive might already be in used to boot coreos.

It's also easier to modify floppy images if the cloud-config needs to be modified, because for example mac os x allows to mount and modify floppy images without any extra tools, while iso images are read only.

I hope this is the right project for the request, if not please tell me were to post is instead.

**Comment by marineam** [comment]
This issue was moved to coreos/bugs#440
