### ISSUE TITLE
compatibility for OpenNebula

### ISSUE THREAD

**Issue by SlavomirPolak** [coreos/coreos-cloudinit#390]
Hello,

I would like to add compatibility for OpenNebula. Are there any standards (rules), that I have to keep, or do you have any hints for me? What do I have to do for you to accept my pull request?

Thanks for your response.

Slavomír Polák

**Comment by crawford** [comment]
Great! Thanks for your help.

Take a look at the other datasources to get an idea of how the code is structured. Other than the golang standards, there really aren't any other rules for the codebase. Just make sure you have tests.

You should also know that we are transitioning to [Ignition](https://github.com/coreos/ignition) with the intent of dropping coreos-cloudinit at some point in the future. You may want to work on that instead, but it's up to you.
